### ISSUE TITLE
Off-by-one error in ulaw.go:101?

### ISSUE THREAD

**Issue by j0z3f** [zaf/g711#1]
First of all, thanks @zaf for this library!

I think found an off-by-one error in ulaw.go on line 101:
https://github.com/zaf/g711/blob/master/ulaw.go#L101
```
    for i, j := 0, 0; j < len(lpcm)-2; i, j = i+1, j+2 {
        ulaw[i] = EncodeUlawFrame(int16(lpcm[j]) | int16(lpcm[j+1])<<8)
    }
```
if `len(lpcm)` is 2, then the for-loop does not run at all. Shoudn't the stop condition be `j <= len(lpcm) - 2`? I am new to audio encodings so I could be wrong.

**Comment by zaf** [comment]
Hello Jozef,

I think you spotted a bug here indeed. The encoder would omit a frame of PCM data in cases like this.
Thank you for that, I just pushed a small fix.
